### ISSUE TITLE
ModuleNotFoundError: No module named ‘flask_socketio’

### ISSUE THREAD

**Issue by MidwestTechnologies** [benbaptist/rtlweb#1]
Ben,

I’ve been wanting to test rtlweb on a Rapsberry Pi 3 B +.  I followed the install instructions including installing flask_socketio but I continue to get the following output:
``
Traceback (most recent call last):
  File "start-rtlweb.py", line 1, in <module>
    from rtlweb import Main
  File "/home/pi/rtlweb/rtlweb/__init__.py", line 6, in <module>
    from rtlweb.dashboard import Dashboard
  File "/home/pi/rtlweb/rtlweb/dashboard/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO, send, emit, join_room, leave_room
ModuleNotFoundError: No module named 'flask_socketio'
``
Please help.  I’m looking forward to testing this on the RPi 3.

Thanks!

Clint, KC9S

**Comment by benbaptist** [comment]
Hey Clint! Sorry for the lack of a response. Completely forgot about checking the Issues tab. 

That's an interesting problem. My first guess is that flask_socketio was installed to a different version of Python than the one that's being used. Are you starting rtlweb with python3, and did you run 'pip3' when installing flask_socketio?
